/**
 * SimpleCarto - Catalogue des pictogrammes thématiques
 * Source : OCHA Humanitarian Icons (UN-OCHA/humanitarian-icons), domaine public (CC0 1.0).
 * Voir ./icons/pictograms/LICENSE.txt et ./icons/pictograms/SOURCE-README.md
 */

const PICTOGRAM_CATEGORIES = [
    { id: "security and incident", label: "Sécurité & incidents (conflits)" },
    { id: "disaster / hazards and crises", label: "Catastrophes & risques naturels" },
    { id: "damage", label: "Dommages & destructions" },
    { id: "people", label: "Personnes & populations" },
    { id: "camp", label: "Camps" },
    { id: "health", label: "Santé" },
    { id: "water sanitation and health; wash", label: "Eau, assainissement & hygiène (WASH)" },
    { id: "food and non-food items", label: "Vivres & biens non alimentaires" },
    { id: "logistics", label: "Logistique" },
    { id: "general infrastructure", label: "Infrastructures générales" },
    { id: "physical barriers", label: "Barrières physiques" },
    { id: "telecommunications and technology", label: "Télécommunications & technologie" },
    { id: "clusters", label: "Clusters (secteurs humanitaires)" },
    { id: "activities / strategy", label: "Activités & stratégie" },
    { id: "socioeconomic and development", label: "Socioéconomie & développement" },
    { id: "lockdown", label: "Confinement & sécurité sanitaire" },
    { id: "product type", label: "Types de produits" },
    { id: "other sectors", label: "Autres secteurs" },
    { id: "ux / ui", label: "Interface & symboles génériques" },
];

const PICTOGRAM_ICONS = [
    { file: "AI-chat.svg", name: "AI chat", category: "ux / ui" },
    { file: "API.svg", name: "API", category: "telecommunications and technology" },
    { file: "Abduction-kidnapping.svg", name: "Abduction kidnapping", category: "security and incident" },
    { file: "About.svg", name: "About", category: "ux / ui" },
    { file: "Add-document.svg", name: "Add document", category: "ux / ui" },
    { file: "Add.svg", name: "Add", category: "ux / ui" },
    { file: "Advocacy.svg", name: "Advocacy", category: "activities / strategy" },
    { file: "Affected-population.svg", name: "Affected population", category: "people" },
    { file: "Agile.svg", name: "Agile", category: "activities / strategy" },
    { file: "Agriculture.svg", name: "Agriculture", category: "other sectors" },
    { file: "Airport-affected.svg", name: "Airport affected", category: "damage" },
    { file: "Airport-closed.svg", name: "Airport closed", category: "lockdown" },
    { file: "Airport-destroyed.svg", name: "Airport destroyed", category: "damage" },
    { file: "Airport-military.svg", name: "Airport military", category: "logistics" },
    { file: "Airport-not-affected.svg", name: "Airport not affected", category: "damage" },
    { file: "Airport.svg", name: "Airport", category: "logistics" },
    { file: "Alert.svg", name: "Alert", category: "ux / ui" },
    { file: "Analysis.svg", name: "Analysis", category: "activities / strategy" },
    { file: "Anticipatory-action.svg", name: "Anticipatory action", category: "activities / strategy" },
    { file: "Apps.svg", name: "Apps", category: "ux / ui" },
    { file: "Arrest-detention.svg", name: "Arrest detention", category: "security and incident" },
    { file: "Assault.svg", name: "Assault", category: "security and incident" },
    { file: "Assembly-point.svg", name: "Assembly point", category: "general infrastructure" },
    { file: "Assessment.svg", name: "Assessment", category: "activities / strategy" },
    { file: "Attack.svg", name: "Attack", category: "security and incident" },
    { file: "Bacteria.svg", name: "Bacteria", category: "health" },
    { file: "Blanket.svg", name: "Blanket", category: "food and non-food items" },
    { file: "Blog.svg", name: "Blog", category: "ux / ui" },
    { file: "Boat.svg", name: "Boat", category: "logistics" },
    { file: "Bookmark.svg", name: "Bookmark", category: "ux / ui" },
    { file: "Border-closed.svg", name: "Border closed", category: "lockdown" },
    { file: "Border-crossing.svg", name: "Border crossing", category: "physical barriers" },
    { file: "Borehole.svg", name: "Borehole", category: "water sanitation and health; wash" },
    { file: "Bottled-water.svg", name: "Bottled water", category: "food and non-food items" },
    { file: "Bridge-affected.svg", name: "Bridge affected", category: "damage" },
    { file: "Bridge-closed.svg", name: "Bridge closed", category: "lockdown" },
    { file: "Bridge-destroyed.svg", name: "Bridge destroyed", category: "damage" },
    { file: "Bridge-not-affected.svg", name: "Bridge not affected", category: "damage" },
    { file: "Bridge.svg", name: "Bridge", category: "logistics" },
    { file: "Bucket.svg", name: "Bucket", category: "food and non-food items" },
    { file: "Buddhist-temple.svg", name: "Buddhist temple", category: "general infrastructure" },
    { file: "Building-closed.svg", name: "Building closed", category: "lockdown" },
    { file: "Building-facility-affected.svg", name: "Building facility affected", category: "damage" },
    { file: "Building-facility-destroyed.svg", name: "Building facility destroyed", category: "damage" },
    { file: "Building-facility-not-affected.svg", name: "Building facility not affected", category: "damage" },
    { file: "Building.svg", name: "Building", category: "general infrastructure" },
    { file: "Bus.svg", name: "Bus", category: "logistics" },
    { file: "COVID-19.svg", name: "COVID 19", category: "health" },
    { file: "CSV-file.svg", name: "CSV file", category: "ux / ui" },
    { file: "Calendar.svg", name: "Calendar", category: "product type" },
    { file: "Camp-Coordination-and-Camp-Management.svg", name: "Camp Coordination and Camp Management", category: "clusters" },
    { file: "Car.svg", name: "Car", category: "logistics" },
    { file: "Carjacking.svg", name: "Carjacking", category: "security and incident" },
    { file: "Case-management.svg", name: "Case management", category: "health" },
    { file: "Cash-transfer.svg", name: "Cash transfer", category: "activities / strategy" },
    { file: "Cell-tower.svg", name: "Cell tower", category: "telecommunications and technology" },
    { file: "Chart.svg", name: "Chart", category: "product type" },
    { file: "Chat.svg", name: "Chat", category: "ux / ui" },
    { file: "Checked-mail.svg", name: "Checked mail", category: "ux / ui" },
    { file: "Checkpoint.svg", name: "Checkpoint", category: "physical barriers" },
    { file: "Child-care-child-friendly.svg", name: "Child care child friendly", category: "other sectors" },
    { file: "Child-combatant.svg", name: "Child combatant", category: "people" },
    { file: "Child-protection.svg", name: "Child protection", category: "other sectors" },
    { file: "Children.svg", name: "Children", category: "people" },
    { file: "Church.svg", name: "Church", category: "general infrastructure" },
    { file: "Civil-military-coordination.svg", name: "Civil military coordination", category: "activities / strategy" },
    { file: "Clinic.svg", name: "Clinic", category: "general infrastructure" },
    { file: "Clothing.svg", name: "Clothing", category: "food and non-food items" },
    { file: "Cold-wave.svg", name: "Cold wave", category: "disaster / hazards and crises" },
    { file: "Communal-latrine.svg", name: "Communal latrine", category: "water sanitation and health; wash" },
    { file: "Community-building.svg", name: "Community building", category: "general infrastructure" },
    { file: "Community-engagement.svg", name: "Community engagement", category: "activities / strategy" },
    { file: "Computer.svg", name: "Computer", category: "telecommunications and technology" },
    { file: "Confined.svg", name: "Confined", category: "lockdown" },
    { file: "Conflict.svg", name: "Conflict", category: "disaster / hazards and crises" },
    { file: "Coordinated-assessement.svg", name: "Coordinated assessement", category: "clusters" },
    { file: "Coordination.svg", name: "Coordination", category: "other sectors" },
    { file: "Copy.svg", name: "Copy", category: "ux / ui" },
    { file: "Country.svg", name: "Country", category: "general infrastructure" },
    { file: "Cyclone.svg", name: "Cyclone", category: "disaster / hazards and crises" },
    { file: "DOCX-file.svg", name: "DOCX file", category: "ux / ui" },
    { file: "Damaged-Affected.svg", name: "Damaged Affected", category: "damage" },
    { file: "Dangerous-area.svg", name: "Dangerous area", category: "security and incident" },
    { file: "Data.svg", name: "Data", category: "product type" },
    { file: "Dead.svg", name: "Dead", category: "people" },
    { file: "Debris-management.svg", name: "Debris management", category: "socioeconomic and development" },
    { file: "Delete-account.svg", name: "Delete account", category: "ux / ui" },
    { file: "Deployment.svg", name: "Deployment", category: "activities / strategy" },
    { file: "Destroyed.svg", name: "Destroyed", category: "damage" },
    { file: "Detergent.svg", name: "Detergent", category: "food and non-food items" },
    { file: "Diplomatic-mission.svg", name: "Diplomatic mission", category: "general infrastructure" },
    { file: "Distribution-site.svg", name: "Distribution site", category: "general infrastructure" },
    { file: "Doctor.svg", name: "Doctor", category: "health" },
    { file: "Document.svg", name: "Document", category: "product type" },
    { file: "Down.svg", name: "Down", category: "ux / ui" },
    { file: "Download.svg", name: "Download", category: "ux / ui" },
    { file: "Drought.svg", name: "Drought", category: "disaster / hazards and crises" },
    { file: "Drowned.svg", name: "Drowned", category: "people" },
    { file: "E-mail.svg", name: "E mail", category: "telecommunications and technology" },
    { file: "Early-Recovery.svg", name: "Early Recovery", category: "clusters" },
    { file: "Earthmound.svg", name: "Earthmound", category: "physical barriers" },
    { file: "Earthquake.svg", name: "Earthquake", category: "disaster / hazards and crises" },
    { file: "Edit.svg", name: "Edit", category: "ux / ui" },
    { file: "Education.svg", name: "Education", category: "clusters" },
    { file: "Elderly.svg", name: "Elderly", category: "people" },
    { file: "Emergency-Telecommunications.svg", name: "Emergency Telecommunications", category: "clusters" },
    { file: "Environment.svg", name: "Environment", category: "other sectors" },
    { file: "Epidemic.svg", name: "Epidemic", category: "disaster / hazards and crises" },
    { file: "Exit-Cancel.svg", name: "Exit Cancel", category: "ux / ui" },
    { file: "Expand-down.svg", name: "Expand down", category: "ux / ui" },
    { file: "Expand-left.svg", name: "Expand left", category: "ux / ui" },
    { file: "Expand-right.svg", name: "Expand right", category: "ux / ui" },
    { file: "Expand-up.svg", name: "Expand up", category: "ux / ui" },
    { file: "Famine.svg", name: "Famine", category: "disaster / hazards and crises" },
    { file: "Favourite.svg", name: "Favourite", category: "ux / ui" },
    { file: "Fax.svg", name: "Fax", category: "telecommunications and technology" },
    { file: "Ferry.svg", name: "Ferry", category: "logistics" },
    { file: "Film.svg", name: "Film", category: "product type" },
    { file: "Filter.svg", name: "Filter", category: "ux / ui" },
    { file: "Financing.svg", name: "Financing", category: "activities / strategy" },
    { file: "Fire.svg", name: "Fire", category: "disaster / hazards and crises" },
    { file: "Fishery.svg", name: "Fishery", category: "other sectors" },
    { file: "Flash-flood.svg", name: "Flash flood", category: "disaster / hazards and crises" },
    { file: "Flood.svg", name: "Flood", category: "disaster / hazards and crises" },
    { file: "Flour.svg", name: "Flour", category: "food and non-food items" },
    { file: "Folder.svg", name: "Folder", category: "ux / ui" },
    { file: "Food-Security.svg", name: "Food Security", category: "clusters" },
    { file: "Food-warehouse.svg", name: "Food warehouse", category: "general infrastructure" },
    { file: "Food.svg", name: "Food", category: "food and non-food items" },
    { file: "Forced-entry.svg", name: "Forced entry", category: "security and incident" },
    { file: "Forced-recruitment.svg", name: "Forced recruitment", category: "security and incident" },
    { file: "Fund.svg", name: "Fund", category: "activities / strategy" },
    { file: "Gap-analysis.svg", name: "Gap analysis", category: "activities / strategy" },
    { file: "Gas-station.svg", name: "Gas station", category: "logistics" },
    { file: "Gender-based-violence.svg", name: "Gender based violence", category: "security and incident" },
    { file: "Gender.svg", name: "Gender", category: "people" },
    { file: "Go.svg", name: "Go", category: "ux / ui" },
    { file: "Government-office.svg", name: "Government office", category: "general infrastructure" },
    { file: "Group.svg", name: "Group", category: "ux / ui" },
    { file: "Handwashing.svg", name: "Handwashing", category: "health" },
    { file: "Harassment-intimidation.svg", name: "Harassment intimidation", category: "security and incident" },
    { file: "Health-facility-affected.svg", name: "Health facility affected", category: "damage" },
    { file: "Health-facility-destroyed.svg", name: "Health facility destroyed", category: "damage" },
    { file: "Health-facility-not-affected.svg", name: "Health facility not affected", category: "damage" },
    { file: "Health-facility.svg", name: "Health facility", category: "general infrastructure" },
    { file: "Health-post.svg", name: "Health post", category: "general infrastructure" },
    { file: "Health-worker.svg", name: "Health worker", category: "health" },
    { file: "Health.svg", name: "Health", category: "clusters" },
    { file: "Heatwave.svg", name: "Heatwave", category: "disaster / hazards and crises" },
    { file: "Heavy-rain.svg", name: "Heavy rain", category: "disaster / hazards and crises" },
    { file: "Helicopter.svg", name: "Helicopter", category: "logistics" },
    { file: "Helipad.svg", name: "Helipad", category: "logistics" },
    { file: "Help.svg", name: "Help", category: "ux / ui" },
    { file: "Hidden.svg", name: "Hidden", category: "ux / ui" },
    { file: "Hindu-temple.svg", name: "Hindu temple", category: "general infrastructure" },
    { file: "Hospital-bed.svg", name: "Hospital bed", category: "health" },
    { file: "Hospital.svg", name: "Hospital", category: "general infrastructure" },
    { file: "Hotel.svg", name: "Hotel", category: "general infrastructure" },
    { file: "House-affected.svg", name: "House affected", category: "damage" },
    { file: "House-burned.svg", name: "House burned", category: "security and incident" },
    { file: "House-destroyed.svg", name: "House destroyed", category: "damage" },
    { file: "House-lockdown.svg", name: "House lockdown", category: "lockdown" },
    { file: "House-not-affected.svg", name: "House not affected", category: "damage" },
    { file: "House.svg", name: "House", category: "general infrastructure" },
    { file: "Humanitarian-access.svg", name: "Humanitarian access", category: "disaster / hazards and crises" },
    { file: "Humanitarian-programme-cycle.svg", name: "Humanitarian programme cycle", category: "activities / strategy" },
    { file: "IDP-refugee-camp.svg", name: "IDP refugee camp", category: "camp" },
    { file: "Indigenous people.svg", name: "Indigenous people", category: "people" },
    { file: "Infant.svg", name: "Infant", category: "people" },
    { file: "Infected.svg", name: "Infected", category: "health" },
    { file: "Infection-control.svg", name: "Infection control", category: "health" },
    { file: "Information-management.svg", name: "Information management", category: "activities / strategy" },
    { file: "Information-technology.svg", name: "Information technology", category: "activities / strategy" },
    { file: "Infrastructure.svg", name: "Infrastructure", category: "general infrastructure" },
    { file: "Injured.svg", name: "Injured", category: "people" },
    { file: "Innovation.svg", name: "Innovation", category: "activities / strategy" },
    { file: "Insect-infestation.svg", name: "Insect infestation", category: "disaster / hazards and crises" },
    { file: "Internally-displaced.svg", name: "Internally displaced", category: "disaster / hazards and crises" },
    { file: "Internet.svg", name: "Internet", category: "telecommunications and technology" },
    { file: "Kitchen-set.svg", name: "Kitchen set", category: "food and non-food items" },
    { file: "Laboratory.svg", name: "Laboratory", category: "health" },
    { file: "Landslide-mudslide.svg", name: "Landslide mudslide", category: "disaster / hazards and crises" },
    { file: "Laptop.svg", name: "Laptop", category: "telecommunications and technology" },
    { file: "Latrine-cabin.svg", name: "Latrine cabin", category: "water sanitation and health; wash" },
    { file: "Leadership.svg", name: "Leadership", category: "activities / strategy" },
    { file: "Learning.svg", name: "Learning", category: "activities / strategy" },
    { file: "Life-saving.svg", name: "Life saving", category: "health" },
    { file: "Link.svg", name: "Link", category: "ux / ui" },
    { file: "Live-geoservices.svg", name: "Live geoservices", category: "telecommunications and technology" },
    { file: "Livelihood.svg", name: "Livelihood", category: "socioeconomic and development" },
    { file: "Livestock.svg", name: "Livestock", category: "socioeconomic and development" },
    { file: "Location-lockdown.svg", name: "Location lockdown", category: "lockdown" },
    { file: "Location.svg", name: "Location", category: "product type" },
    { file: "Locust-infestation.svg", name: "Locust infestation", category: "disaster / hazards and crises" },
    { file: "Logistics.svg", name: "Logistics", category: "clusters" },
    { file: "Map.svg", name: "Map", category: "product type" },
    { file: "Market-closed.svg", name: "Market closed", category: "lockdown" },
    { file: "Market.svg", name: "Market", category: "general infrastructure" },
    { file: "Mask.svg", name: "Mask", category: "health" },
    { file: "Mattress.svg", name: "Mattress", category: "food and non-food items" },
    { file: "Medical-supply.svg", name: "Medical supply", category: "food and non-food items" },
    { file: "Medicine.svg", name: "Medicine", category: "food and non-food items" },
    { file: "Meeting.svg", name: "Meeting", category: "activities / strategy" },
    { file: "Menu.svg", name: "Menu", category: "ux / ui" },
    { file: "Military-gate.svg", name: "Military gate", category: "physical barriers" },
    { file: "Mine.svg", name: "Mine", category: "security and incident" },
    { file: "Missing.svg", name: "Missing", category: "people" },
    { file: "Mobile-clinic.svg", name: "Mobile clinic", category: "general infrastructure" },
    { file: "Mobile-phone.svg", name: "Mobile phone", category: "telecommunications and technology" },
    { file: "Monitor.svg", name: "Monitor", category: "telecommunications and technology" },
    { file: "Monitoring.svg", name: "Monitoring", category: "activities / strategy" },
    { file: "More-options.svg", name: "More options", category: "ux / ui" },
    { file: "Mosque.svg", name: "Mosque", category: "general infrastructure" },
    { file: "Mosquito-net.svg", name: "Mosquito net", category: "food and non-food items" },
    { file: "Multi-cluster-sector.svg", name: "Multi cluster sector", category: "clusters" },
    { file: "Murder.svg", name: "Murder", category: "security and incident" },
    { file: "NGO-office.svg", name: "NGO office", category: "general infrastructure" },
    { file: "National-army.svg", name: "National army", category: "people" },
    { file: "Needs-assessment.svg", name: "Needs assessment", category: "activities / strategy" },
    { file: "Next-item.svg", name: "Next item", category: "ux / ui" },
    { file: "Non-food-items-2.svg", name: "Non food items 2", category: "food and non-food items" },
    { file: "Non-food-items.svg", name: "Non food items", category: "food and non-food items" },
    { file: "Not-affected.svg", name: "Not affected", category: "damage" },
    { file: "Not-infected.svg", name: "Not infected", category: "health" },
    { file: "Not-secured.svg", name: "Not secured", category: "security and incident" },
    { file: "Notification.svg", name: "Notification", category: "ux / ui" },
    { file: "Nutrition.svg", name: "Nutrition", category: "clusters" },
    { file: "Observation-tower.svg", name: "Observation tower", category: "physical barriers" },
    { file: "Oil-facility.svg", name: "Oil facility", category: "general infrastructure" },
    { file: "Oil.svg", name: "Oil", category: "food and non-food items" },
    { file: "Out-of-platform.svg", name: "Out of platform", category: "ux / ui" },
    { file: "P-code.svg", name: "P code", category: "activities / strategy" },
    { file: "PDF-file.svg", name: "PDF file", category: "ux / ui" },
    { file: "Partnership.svg", name: "Partnership", category: "activities / strategy" },
    { file: "Password.svg", name: "Password", category: "ux / ui" },
    { file: "Pause.svg", name: "Pause", category: "ux / ui" },
    { file: "Peacekeeping-force.svg", name: "Peacekeeping force", category: "people" },
    { file: "People-affected.svg", name: "People affected", category: "people" },
    { file: "People-covered.svg", name: "People covered", category: "people" },
    { file: "People-in-need-2.svg", name: "People in need 2", category: "people" },
    { file: "People-in-need.svg", name: "People in need", category: "people" },
    { file: "People-reached.svg", name: "People reached", category: "people" },
    { file: "People-targeted-2.svg", name: "People targeted 2", category: "people" },
    { file: "People-targeted.svg", name: "People targeted", category: "people" },
    { file: "People-with-physical-impairments.svg", name: "People with physical impairments", category: "people" },
    { file: "Permanent-camp.svg", name: "Permanent camp", category: "camp" },
    { file: "Person-1.svg", name: "Person 1", category: "people" },
    { file: "Person-2.svg", name: "Person 2", category: "people" },
    { file: "Photo.svg", name: "Photo", category: "product type" },
    { file: "Physical-closure.svg", name: "Physical closure", category: "physical barriers" },
    { file: "Physical-distancing.svg", name: "Physical distancing", category: "lockdown" },
    { file: "Plastic-sheeting.svg", name: "Plastic sheeting", category: "food and non-food items" },
    { file: "Police-station.svg", name: "Police station", category: "general infrastructure" },
    { file: "Policy.svg", name: "Policy", category: "activities / strategy" },
    { file: "Population-growth.svg", name: "Population growth", category: "socioeconomic and development" },
    { file: "Population-return.svg", name: "Population return", category: "disaster / hazards and crises" },
    { file: "Port-affected.svg", name: "Port affected", category: "damage" },
    { file: "Port-closed.svg", name: "Port closed", category: "lockdown" },
    { file: "Port-destroyed.svg", name: "Port destroyed", category: "damage" },
    { file: "Port-not-affected.svg", name: "Port not affected", category: "damage" },
    { file: "Port.svg", name: "Port", category: "logistics" },
    { file: "Potable-water-source.svg", name: "Potable water source", category: "water sanitation and health; wash" },
    { file: "Potable-water.svg", name: "Potable water", category: "water sanitation and health; wash" },
    { file: "Poverty.svg", name: "Poverty", category: "disaster / hazards and crises" },
    { file: "Power-electricity-affected.svg", name: "Power electricity affected", category: "damage" },
    { file: "Power-electricity-not-affected.svg", name: "Power electricity not affected", category: "damage" },
    { file: "Power-electricity.svg", name: "Power electricity", category: "general infrastructure" },
    { file: "Power-outage.svg", name: "Power outage", category: "damage" },
    { file: "Pregnant.svg", name: "Pregnant", category: "people" },
    { file: "Preparedness.svg", name: "Preparedness", category: "activities / strategy" },
    { file: "Previous-item.svg", name: "Previous item", category: "ux / ui" },
    { file: "Print.svg", name: "Print", category: "ux / ui" },
    { file: "Protection.svg", name: "Protection", category: "clusters" },
    { file: "Public-information.svg", name: "Public information", category: "activities / strategy" },
    { file: "Radio.svg", name: "Radio", category: "telecommunications and technology" },
    { file: "Rebel.svg", name: "Rebel", category: "people" },
    { file: "Reconstruction.svg", name: "Reconstruction", category: "socioeconomic and development" },
    { file: "Refugee.svg", name: "Refugee", category: "disaster / hazards and crises" },
    { file: "Registration.svg", name: "Registration", category: "camp" },
    { file: "Relief-goods.svg", name: "Relief goods", category: "food and non-food items" },
    { file: "Remote-support.svg", name: "Remote support", category: "telecommunications and technology" },
    { file: "Remove-document.svg", name: "Remove document", category: "ux / ui" },
    { file: "Remove.svg", name: "Remove", category: "ux / ui" },
    { file: "Report.svg", name: "Report", category: "product type" },
    { file: "Reporting.svg", name: "Reporting", category: "activities / strategy" },
    { file: "Resettlement.svg", name: "Resettlement", category: "people" },
    { file: "Resilience.svg", name: "Resilience", category: "activities / strategy" },
    { file: "Respiratory.svg", name: "Respiratory", category: "health" },
    { file: "Response.svg", name: "Response", category: "activities / strategy" },
    { file: "Return.svg", name: "Return", category: "ux / ui" },
    { file: "Rice.svg", name: "Rice", category: "food and non-food items" },
    { file: "Road-affected.svg", name: "Road affected", category: "damage" },
    { file: "Road-barrier.svg", name: "Road barrier", category: "physical barriers" },
    { file: "Road-closed.svg", name: "Road closed", category: "lockdown" },
    { file: "Road-destroyed.svg", name: "Road destroyed", category: "damage" },
    { file: "Road-not-affected.svg", name: "Road not affected", category: "damage" },
    { file: "Road.svg", name: "Road", category: "logistics" },
    { file: "Roadblock.svg", name: "Roadblock", category: "physical barriers" },
    { file: "Robbery.svg", name: "Robbery", category: "security and incident" },
    { file: "Rule-of-law-and-justice.svg", name: "Rule of law and justice", category: "other sectors" },
    { file: "Rural-exodus.svg", name: "Rural exodus", category: "socioeconomic and development" },
    { file: "Rural.svg", name: "Rural", category: "socioeconomic and development" },
    { file: "Safety-and-security.svg", name: "Safety and security", category: "other sectors" },
    { file: "Salt.svg", name: "Salt", category: "food and non-food items" },
    { file: "Sanitation.svg", name: "Sanitation", category: "water sanitation and health; wash" },
    { file: "Sanitizer.svg", name: "Sanitizer", category: "health" },
    { file: "Satellite-dish.svg", name: "Satellite dish", category: "telecommunications and technology" },
    { file: "Save.svg", name: "Save", category: "ux / ui" },
    { file: "Scale-down-operation.svg", name: "Scale down operation", category: "activities / strategy" },
    { file: "Scale-up-operation.svg", name: "Scale up operation", category: "activities / strategy" },
    { file: "School-affected.svg", name: "School affected", category: "damage" },
    { file: "School-closed.svg", name: "School closed", category: "lockdown" },
    { file: "School-destroyed.svg", name: "School destroyed", category: "damage" },
    { file: "School-not-affected.svg", name: "School not affected", category: "damage" },
    { file: "School.svg", name: "School", category: "general infrastructure" },
    { file: "Search-and-rescue.svg", name: "Search and rescue", category: "activities / strategy" },
    { file: "Search.svg", name: "Search", category: "ux / ui" },
    { file: "Secured.svg", name: "Secured", category: "security and incident" },
    { file: "Security.svg", name: "Security", category: "security and incident" },
    { file: "See.svg", name: "See", category: "ux / ui" },
    { file: "Selected.svg", name: "Selected", category: "ux / ui" },
    { file: "Services-and-tools.svg", name: "Services and tools", category: "activities / strategy" },
    { file: "Settings.svg", name: "Settings", category: "ux / ui" },
    { file: "Sex.svg", name: "Sex", category: "people" },
    { file: "Sexual-and-reproductive health.svg", name: "Sexual and reproductive health", category: "activities / strategy" },
    { file: "Sexual-violence.svg", name: "Sexual violence", category: "security and incident" },
    { file: "Share.svg", name: "Share", category: "ux / ui" },
    { file: "Shelter.svg", name: "Shelter", category: "clusters" },
    { file: "Ship.svg", name: "Ship", category: "logistics" },
    { file: "Shower.svg", name: "Shower", category: "water sanitation and health; wash" },
    { file: "Smartphone.svg", name: "Smartphone", category: "telecommunications and technology" },
    { file: "Snow-avalanche.svg", name: "Snow avalanche", category: "disaster / hazards and crises" },
    { file: "Snowfall.svg", name: "Snowfall", category: "disaster / hazards and crises" },
    { file: "Soap.svg", name: "Soap", category: "food and non-food items" },
    { file: "Solid-waste.svg", name: "Solid waste", category: "water sanitation and health; wash" },
    { file: "Spontaneous-site.svg", name: "Spontaneous site", category: "camp" },
    { file: "Spring-water.svg", name: "Spring water", category: "water sanitation and health; wash" },
    { file: "Staff-management.svg", name: "Staff management", category: "activities / strategy" },
    { file: "Stop.svg", name: "Stop", category: "ux / ui" },
    { file: "Storm-surge.svg", name: "Storm surge", category: "disaster / hazards and crises" },
    { file: "Storm.svg", name: "Storm", category: "disaster / hazards and crises" },
    { file: "Stove.svg", name: "Stove", category: "food and non-food items" },
    { file: "Submersible-pump.svg", name: "Submersible pump", category: "water sanitation and health; wash" },
    { file: "Sugar.svg", name: "Sugar", category: "food and non-food items" },
    { file: "Table.svg", name: "Table", category: "product type" },
    { file: "Tarpaulin.svg", name: "Tarpaulin", category: "food and non-food items" },
    { file: "Technological-disaster.svg", name: "Technological disaster", category: "disaster / hazards and crises" },
    { file: "Temporary-camp.svg", name: "Temporary camp", category: "camp" },
    { file: "Tent.svg", name: "Tent", category: "food and non-food items" },
    { file: "Testing.svg", name: "Testing", category: "health" },
    { file: "Time.svg", name: "Time", category: "ux / ui" },
    { file: "Toilet.svg", name: "Toilet", category: "water sanitation and health; wash" },
    { file: "Top-ranking.svg", name: "Top ranking", category: "activities / strategy" },
    { file: "Tornado.svg", name: "Tornado", category: "disaster / hazards and crises" },
    { file: "Trade-and-market.svg", name: "Trade and market", category: "socioeconomic and development" },
    { file: "Train.svg", name: "Train", category: "logistics" },
    { file: "Training.svg", name: "Training", category: "activities / strategy" },
    { file: "Transition-site.svg", name: "Transition site", category: "camp" },
    { file: "Trending.svg", name: "Trending", category: "ux / ui" },
    { file: "Truck.svg", name: "Truck", category: "logistics" },
    { file: "Tsunami.svg", name: "Tsunami", category: "disaster / hazards and crises" },
    { file: "Tunnel.svg", name: "Tunnel", category: "logistics" },
    { file: "UN-compound-office.svg", name: "UN compound office", category: "general infrastructure" },
    { file: "UN-vehicle.svg", name: "UN vehicle", category: "logistics" },
    { file: "University.svg", name: "University", category: "general infrastructure" },
    { file: "Up.svg", name: "Up", category: "ux / ui" },
    { file: "Upload.svg", name: "Upload", category: "ux / ui" },
    { file: "Urban-rural.svg", name: "Urban rural", category: "socioeconomic and development" },
    { file: "Urban.svg", name: "Urban", category: "socioeconomic and development" },
    { file: "User.svg", name: "User", category: "ux / ui" },
    { file: "Users.svg", name: "Users", category: "ux / ui" },
    { file: "Vaccine.svg", name: "Vaccine", category: "food and non-food items" },
    { file: "Validate-account.svg", name: "Validate account", category: "ux / ui" },
    { file: "Ventilator.svg", name: "Ventilator", category: "health" },
    { file: "Video.svg", name: "Video", category: "product type" },
    { file: "Violent-wind.svg", name: "Violent wind", category: "disaster / hazards and crises" },
    { file: "Virus.svg", name: "Virus", category: "health" },
    { file: "Volcano.svg", name: "Volcano", category: "disaster / hazards and crises" },
    { file: "Walkie-talkie.svg", name: "Walkie talkie", category: "telecommunications and technology" },
    { file: "Warning-Error.svg", name: "Warning Error", category: "ux / ui" },
    { file: "Water-Sanitation-and-Hygiene.svg", name: "Water Sanitation and Hygiene", category: "clusters" },
    { file: "Water-source.svg", name: "Water source", category: "water sanitation and health; wash" },
    { file: "Water-trucking.svg", name: "Water trucking", category: "water sanitation and health; wash" },
    { file: "Work-from-home.svg", name: "Work from home", category: "telecommunications and technology" },
    { file: "Worm-infestation.svg", name: "Worm infestation", category: "disaster / hazards and crises" },
    { file: "XLSX-file.svg", name: "XLSX file", category: "ux / ui" },
    { file: "ZIP-compressed.svg", name: "ZIP compressed", category: "ux / ui" },
];
